advanced_class_based_views/adv_cbv/urls.py
from django.urls import path
from adv_cbv import views

app_name = 'adv_cbv'

urlpatterns = [
    path('', views.SchoolListView.as_view(), name='list'),
    path('<pk>', views.SchoolDetailView.as_view(), name='detail'),
    path('create/', views.SchoolCreateView.as_view(), name='create'),
    path('update/<pk>', views.SchoolUpdateView.as_view(), name='update'),
    path('delete/<pk>', views.SchoolDeleteView.as_view(), name='delete')
]

advanced_class_based_views/advanced_class_based_views/urls.py
from django.contrib import admin
from django.urls import path, include
from adv_cbv import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.IndexView.as_view()),
    path('adv_cbv/', include('adv_cbv.urls', namespace='adv_cbv'))
]

advanced_class_based_views/adv_cbv/models.py
from django.db import models

# Create your models here.
from django.urls import reverse


class School(models.Model):
    name = models.CharField(max_length=256)
    principal = models.CharField(max_length=256)
    location = models.CharField(max_length=256)

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("adv_cbv:detail", kwargs={'pk': self.pk})


class Student(models.Model):
    name = models.CharField(max_length=256)
    age = models.PositiveIntegerField()
    school = models.ForeignKey(School, related_name='students', on_delete=models.CASCADE)

    def __str__(self):
        return self.name

advanced_class_based_views/adv_cbv/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import (View, TemplateView,
                                  ListView, DetailView,
                                  CreateView, UpdateView,
                                  DeleteView)
from . import models

class IndexView(TemplateView):
    template_name = 'index.html'

class SchoolListView(ListView):
    context_object_name = 'schools'
    model = models.School

class SchoolDetailView(DetailView):
    context_object_name = 'school_detail'
    model = models.School
    template_name = 'adv_cbv/school_detail.html'

class SchoolCreateView(CreateView):
    fields = ('name', 'principal', 'location')
    model = models.School

class SchoolUpdateView(UpdateView):
    fields = ('name', 'principal')
    model = models.School

class SchoolDeleteView(DeleteView):
    model = models.School
    success_url = reverse_lazy('adv_cbv:list')

advanced_class_based_views/adv_cbv/templates/adv_cbv/adv_cbv_base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Base</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container collapse navbar-collapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item"><a class="navbar-brand" href="{% url 'adv_cbv:list' %}">Schools</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'admin:index' %}">Admin</a></li>
            </ul>
        </div>
    </nav>
    <div class="container">
        {% block body_block %}
        {% endblock %}
    </div>

</body>
</html>

advanced_class_based_views/adv_cbv/templates/adv_cbv/school_confirm_delete.html
<!DOCTYPE html>
{% extends 'adv_cbv/adv_cbv_base.html' %}

{% block body_block %}

<h1>Delete {{ school.name }}?</h1>
<form method="POST">
    {% csrf_token %}
    <input type="submit" class="btn btn-danger" value="Delete">
    <a href="{% url 'adv_cbv:detail' pk=school.pk %}">Cancel</a>
</form>

{% endblock %}

advanced_class_based_views/adv_cbv/templates/adv_cbv/school_detail.html
<!DOCTYPE html>
{% extends 'adv_cbv/adv_cbv_base.html' %}
{% block body_block %}

<div class="jumbotron">
    <h1>Welcome to the School Detail Page</h1>
    <h2>School Details:</h2>
    <p>{{ school_detail.name }}</p>
    <p>{{ school_detail.principal }}</p>
    <p>{{ school_detail.location }}</p>
    <h3>Students:</h3>

    {% for student in school_detail.students.all %}
    <p>{{ student.name }} who is {{ student.age }} years old.</p>
    {% endfor %}

</div>
<div class="container">
    <p><a class="btn btn-warning" href="{% url 'adv_cbv:update' pk=school_detail.pk %}">Update</a></p>
    <p><a class="btn btn-danger" href="{% url 'adv_cbv:delete' pk=school_detail.pk %}">Delete</a></p>
</div>

{% endblock %}

advanced_class_based_views/adv_cbv/templates/adv_cbv/school_form.html
<!DOCTYPE html>
{% extends 'adv_cbv/adv_cbv_base.html' %}

{% block body_block %}

<h1>
    {% if not form.instance.pk %}
    Create School
    {% else %}
    Update School
    {% endif %}
</h1>

<form method="POST">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" class="btn btn-primary" value="Submit">
</form>

{% endblock %}

advanced_class_based_views/adv_cbv/templates/adv_cbv/school_list.html
<!DOCTYPE html>
{% extends 'adv_cbv/adv_cbv_base.html' %}

{% block body_block %}

<h1>Welcome to the list of all the schools!</h1>
<ol>
    {% for school in schools %}
    <h2><li><a href="{{ school.id }}">{{ school.name }}</a></li></h2>
    {% endfor %}
</ol>

{% endblock %}

advanced_class_based_views/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Base</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container collapse navbar-collapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item"><a class="navbar-brand" href="{% url 'adv_cbv:list' %}">Schools</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'admin:index' %}">Admin</a></li>
            </ul>
        </div>
    </nav>
    <div class="container">
        {% block body_block %}
        {% endblock %}
    </div>

</body>
</html>

advanced_class_based_views/templates/index.html
<!DOCTYPE html>
{% extends 'base.html' %}
{% block body_block %}
    <div class="jumbotron">
        <h1>Home Page!</h1>
    </div>
{% endblock %}